WEB_953506_Kruglaya/Components/CartViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WEB_953506_Kruglaya.Extensions;
using WEB_953506_Kruglaya.Models;

namespace WEB_953506_Kruglaya.Components
{
    public class CartViewComponent: ViewComponent
    {
        private Cart _cart;
        public CartViewComponent(Cart cart)
        {
            _cart = cart;
        }
        public IViewComponentResult Invoke()
        {
            
            return View(_cart);
        }
    }
}

WEB_953506_Kruglaya/Components/MenuViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WEB_953506_Kruglaya.Components
{
    public class MenuViewComponent: ViewComponent
    {
        private List<Models.MenuItem> _menuItems = new List<Models.MenuItem>
        {
            new Models.MenuItem{ Controller="Home", Action="Index", Text="Lab 6"},
            new Models.MenuItem{ Controller="Moovie", Action="Index_my", Text="Moovies"},
            new Models.MenuItem{ IsPage=true, Area="Admin", Page="/Index", Text="Администрирование"}
        };

        public IViewComponentResult Invoke()
        {
            var controller = ViewContext.RouteData.Values["controller"];
            var page = ViewContext.RouteData.Values["page"];
            var area = ViewContext.RouteData.Values["area"];

            foreach(var item in _menuItems)
            {
                var _matchController = controller?.Equals(item.Controller) ?? false;

                var _matchArea = area?.Equals(item.Area) ?? false;

                if(_matchController || _matchArea)
                {
                    item.Active = "active";
                }
            }
            return View(_menuItems);
        }
    }
}

WEB_953506_Kruglaya/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <header>
        <div class="container">
            <nav class="navbar navbar-dark navbar-expand-md">
                <a class="navbar-brand" asp-action="Index" asp-controller="Home">
                    WebLabsV06
                </a>
                    @await Component.InvokeAsync("Menu")
                <partial name="_UserPartial" />
            </nav>
        </div>
    </header>
    <main class="container">
        @RenderBody()
    </main>
    <footer class="fixed-bottom">
        <div class="navbar navbar-dark  navbar-expand-md">
            <div class="container">
                <div class="navbar-nav ml-auto">
                    <a class="nav-item nav-link" href="http://www.facebook.com">
                        <i class="fab fa-facebook-f fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.vk.com">
                        <i class="fab fa-vk fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.twitter.com">
                        <i class="fab fa-twitter fa-2x"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WEB_953506_Kruglaya/Views/Shared/_UserPartial.cshtml
@using Microsoft.AspNetCore.Identity;
@using WEB_953506_Kruglaya.Entities;
@inject SignInManager<ApplicationUser> signInManager

@if (signInManager.IsSignedIn(User))
{

        @await Component.InvokeAsync("Cart")

    <div class="dropdown ml-4 nav-color">
        <div class="dropdown-toggle" id="dropdownMenuButton"
             data-toggle="dropdown" aria-haspopup="true"
             aria-expanded="false">
            <img img-action="GetAvatar"
                 img-controller="Image"
                 width="30" alt="User"
                 class="rounded bg-light" />
        </div>
        <div class="dropdown-menu"
                aria-labelledby="dropdownMenuButton">
            <div class="dropdown-item-text">
                <img img-action="GetAvatar"
                     img-controller="Image"
                     width="30" alt="User"
                     class="rounded bg-light" />
                @User.Identity.Name
            </div>
            <div class="dropdown-divider"></div>
                <a class="dropdown-item" asp-controller="Home" asp-action="Index">Мои фильмы</a>
                <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnurl="@ViewContext.HttpContext.Request.Path">
                    <input type="submit" value="Log off" class="dropdown-item" />
                </form>
        </div>
        
    </div>
}
else
            {
<ul class="nav navbar-nav ml-auto">
    <li>
        <a class="nav-item nav-link"
           asp-area="Identity"
           asp-page="/Account/Login">
            Войти
        </a>
    </li>
    <li>
        <a class="nav-item nav-link"
           asp-area="Identity"
           asp-page="/Account/Register">
            Зарегистрироваться
        </a>
    </li>
</ul>
            }