WEB_953506_Kruglaya/Entities/Moovie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WEB_953506_Kruglaya.Entities
{
    public class Moovie
    {
        public int ID { get; set; } = 0;
        public string Name { get; set; } = "";
        public string Description { get; set; } = "";
        public string Image { get; set; } = "";
        public int CategoryID { get; set; } = 0;
        public Category Category_ { get; set; }
        private int _time;

        public int Time
        {
            get
            {
                return _time;
            }
            set
            {
                if (value > 0)
                {
                    _time = value;
                }
            }
        }
    }
}

WEB_953506_Kruglaya/Controllers/CartController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WEB_953506_Kruglaya.Data;
using WEB_953506_Kruglaya.Extensions;
using WEB_953506_Kruglaya.Models;

namespace WEB_953506_Kruglaya.Controllers
{
    public class CartController : Controller
    {
        private ApplicationDbContext _context;
        private Cart _cart;
        private string cartKey = "cart";

        public CartController(ApplicationDbContext context, Cart cart)
        {
            _context = context;
            _cart = cart;
        }

        public IActionResult Index()
        {
            return View(_cart.Items.Values);
        }

        [Microsoft.AspNetCore.Authorization.Authorize]
        public IActionResult Add(int id, string returnUrl)
        {
            


            var item = _context.Moovies.Find(id);
            if (item != null)
            {
                _cart.AddtoCart(item);
               
            }
            return Redirect(returnUrl);
        }
        public IActionResult Delete(int id)
        {
            _cart.RemovefromCart(id);
            return RedirectToAction("Index");
        }

       
    }
}

WEB_953506_Kruglaya/Controllers/MoovieController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WEB_953506_Kruglaya.Entities;
using WEB_953506_Kruglaya.Models;
using WEB_953506_Kruglaya.Extensions;
using WEB_953506_Kruglaya.Data;
using Microsoft.Extensions.Logging;

namespace WEB_953506_Kruglaya.Controllers
{
    public class MoovieController : Controller
    {
        ApplicationDbContext _context;
        int _pageSize;

        public MoovieController(ApplicationDbContext context, ILogger<MoovieController> logger)
        {
            _pageSize = 3;
            _context = context;
        }

        [Route("Moovie/Index_my")]
        [Route("page_{page}")]
        public IActionResult Index_my(int? categories, int page=1)
        {
            var mooviesFilt = _context.Moovies
                .Where(m => !categories.HasValue || m.CategoryID == categories.Value);
            ViewData["Text"] = "MoovieController";
            ViewData["Categories"] = _context.Categories;
            ViewData["CurrentCategory"] = categories ?? 0;
            var model = ListViewModel<Moovie>.GetModel(mooviesFilt, page, _pageSize);
            if (Request.IsAjaxRequest())
                return PartialView("_listpartial", model);
            else
                return View(model);
        }
    }
}

WEB_953506_Kruglaya/Views/Moovie/Index_my.cshtml
@model ListViewModel<Moovie>

@{
    ViewData["Title"] = "Подборка";
    var categories = ViewData["Categories"] as IEnumerable<Category>;
    int currentCategory = (int)ViewData["CurrentCategory"];
    var text = currentCategory != 0
    ? categories
    .FirstOrDefault(g => g.CategoryId == currentCategory)?
    .CategoryName
    : "Все";
}


<div class="row">
    <div class="col-2">
        <div class="dropdown mt-2">
            <a class="btn btn-secondary dropdown-toggle"
               asp-action="Index_my" asp-controller="Moovie"
               role="button"
               id="dropdownMenuLink"
               data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                @text
            </a>
            <div class="dropdown-menu"
                 aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item"
                   asp-action="Index_my"
                   asp-controller="Moovie">Все</a>
                @foreach (var item in categories)
                {
                    <a class="dropdown-item"
                       asp-action="Index_my"
                       asp-controller="Moovie"
                       asp-route-categories="@item.CategoryId"
                       asp-route-page="1">@item.CategoryName</a>
                }
            </div>
        </div>
    </div>
    <div class="col-10">
        <div class="card-group" id="list">
                <partial name="_ListPartial" model="@Model" />
        </div>
        <pager page-current="@Model.CurrentPage" page-total="@Model.AllPages" action="Index_my" controller="Moovie" category-id="@currentCategory"/>
    </div>
</div>

WEB_953506_Kruglaya/Views/Moovie/_ListItemPartial.cshtml
@model WEB_953506_Kruglaya.Entities.Moovie

<div class='card m-3 p-1 text-center col-5'>
    <img src="~/Images/@Model.Image"
         alt='...'
         class="card-img-top h-75 w-100" />
    <div class="card-footer">
        <h5 class="card-title">
            @Model.Name
        </h5>
        <p class="card-text">
            @Model.Description
        </p>
        <div class="card-text badge badge-secondary">
            <h6>@Model.Time минут</h6>
        </div>
        @{ 
            var request = ViewContext.HttpContext.Request;
            var returnUrl = request.Path +
            request.QueryString.ToUriComponent();
        }
        <p class="mt-2">
            <a asp-action="Add"
               asp-controller="Cart"
               asp-route-id="@Model.ID"
               asp-route-returnUrl="@returnUrl"
               class="btn btn-primary">
                <i class="fa fa-tv"></i> Cмотреть
            </a>
        </p>
    </div>
</div>

WEB_953506_Kruglaya/Views/Moovie/_ListPartial.cshtml
@model ListViewModel<Moovie>

@foreach (var item in Model)
{
    <partial name="_ListItemPartial" model="@item" />
}